services:
  db:
    image: postgres:17
    container_name: database
    environment:
      - POSTGRES_USER=intro
      - POSTGRES_PASSWORD=contraseña_segura
      - POSTGRES_DB=adopciones
    ports:
      - 5432:5432
    volumes:
      - ./psql_data:/var/lib/postgresql/data
  app:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://intro:contraseña_segura@db:5432/adopciones
    depends_on:
      - db
